# Generated by Django 3.0.5 on 2022-10-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoData',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateField()),
                ('channel_name', models.CharField(max_length=100)),
                ('thumbnail_url', models.URLField()),
            ],
            options={
                'db_table': 'video_data',
            },
        ),
    ]
