# Generated by Django 3.0.5 on 2022-10-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_trend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodata',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
