# Generated by Django 3.0.5 on 2022-10-10 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_trend', '0002_auto_20221010_0808'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='videodata',
            table='video',
        ),
    ]
