# Generated by Django 3.0.5 on 2022-10-10 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_trend', '0003_auto_20221010_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='youtube_trend.VideoData')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
