# Generated by Django 3.0.5 on 2022-10-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_trend', '0004_commentdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodata',
            name='rank',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
