# Generated by Django 3.0.5 on 2022-10-14 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_trend', '0006_dailyrankdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videodata',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='videodata',
            name='rank',
        ),
    ]
