# Generated by Django 3.0.5 on 2022-10-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_trend', '0007_auto_20221014_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrankdata',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
