# Generated by Django 3.0.5 on 2022-10-14 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_trend', '0008_auto_20221014_2046'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dailyrankdata',
            table='daily_rank',
        ),
    ]
