# Generated by Django 3.0.5 on 2022-10-14 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_trend', '0012_auto_20221014_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyrankdata',
            old_name='video_id',
            new_name='video',
        ),
    ]
