# Generated by Django 3.0.5 on 2022-10-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_trend', '0013_auto_20221014_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videodata',
            name='description',
        ),
        migrations.AlterField(
            model_name='videodata',
            name='title',
            field=models.TextField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='dailyrankdata',
            constraint=models.UniqueConstraint(fields=('date', 'rank'), name='date_rank_unique'),
        ),
    ]
