# Generated by Django 3.0.5 on 2022-10-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_trend', '0014_auto_20221017_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentdata',
            name='comment',
        ),
        migrations.AddField(
            model_name='commentdata',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commentdata',
            name='word',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name='commentdata',
            constraint=models.UniqueConstraint(fields=('video_id', 'word'), name='video_word_unique'),
        ),
    ]
