/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface RankVideoData
 */
export interface RankVideoData {
    /**
     * 
     * @type {string}
     * @memberof RankVideoData
     */
    'date': string;
    /**
     * 
     * @type {number}
     * @memberof RankVideoData
     */
    'rank': number;
    /**
     * 
     * @type {string}
     * @memberof RankVideoData
     */
    'created_at': string;
    /**
     * 
     * @type {VideoData}
     * @memberof RankVideoData
     */
    'video': VideoData;
}
/**
 * 
 * @export
 * @interface VideoData
 */
export interface VideoData {
    /**
     * 
     * @type {string}
     * @memberof VideoData
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof VideoData
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof VideoData
     */
    'description'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VideoData
     */
    'channel_name': string;
    /**
     * 
     * @type {string}
     * @memberof VideoData
     */
    'thumbnail_url': string;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary getDailyRankVideoDataList
         * @param {string} date 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDailyRankVideoDataList: async (date: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'date' is not null or undefined
            assertParamExists('getDailyRankVideoDataList', 'date', date)
            const localVarPath = `/api/v1/video/{date}/`
                .replace(`{${"date"}}`, encodeURIComponent(String(date)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary getDailyRankVideoDataList
         * @param {string} date 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDailyRankVideoDataList(date: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<RankVideoData>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDailyRankVideoDataList(date, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary getDailyRankVideoDataList
         * @param {string} date 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDailyRankVideoDataList(date: string, options?: any): AxiosPromise<Array<RankVideoData>> {
            return localVarFp.getDailyRankVideoDataList(date, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary getDailyRankVideoDataList
     * @param {string} date 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getDailyRankVideoDataList(date: string, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getDailyRankVideoDataList(date, options).then((request) => request(this.axios, this.basePath));
    }
}


